### ISSUE TITLE
Add CNAME record for www

### ISSUE THREAD

**Issue by aburgel** [django-nonrel/django-nonrel.github.com#3]
looks like we need a CNAME record to get www.django-nonrel.org to work. can you add it?

it should point to django-nonrel.github.com

**Comment by jonashaag** [comment]
Done. Not sure if we need to update the CNAME file, we'll see when the DNS entries are updated.

**Comment by fhahn** [comment]
http://www.django-nonrel.org/ still does not work.

I think we'll have to add an DNS record for the subdomain www.django-nonrel.org that points to the Github page.

**Comment by jonashaag** [comment]
Hm it has a CNAME that points to the same IP, isn't that what I need to do?

**Comment by fhahn** [comment]
I think there should be a CNAME entry for www.django-nonrel.org that points to django-nonrel.github.com, at least it works for me this way.

cheers

(https://help.github.com/articles/setting-up-a-custom-domain-with-pages)

**Comment by jonashaag** [comment]
Added CNAME to django-nonrel.github.com, does it work now?

**Comment by fhahn** [comment]
Jep it works now (http://www.django-nonrel.org redirects to http://django-nonrel.org)
